const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const nodemailer = require("nodemailer");
const PDFDocument = require("pdfkit");

const app = express();
const PORT = process.env.PORT || 10000;

app.use(cors());
app.use(bodyParser.json());

app.post("/api/generate", async (req, res) => {
  const formData = req.body;

  // ------------------ 1. PROMPT GENERATION ------------------
  const prompt = `
You are a certified resume and cover letter writing expert with deep understanding of ATS standards and global hiring expectations. Based on the provided profile, generate:

1. A professionally formatted, ATS-friendly resume with clearly defined sections including:
   - Title: Resume (center-aligned and bold)
   - Full Name and Contact Info
   - Professional Summary
   - Skills
   - Professional Experience
   - Education

2. A tailored and compelling cover letter addressed to the hiring manager at the specified company.

---

Resume
${formData.fullName}
${formData.jobTitle} | ${formData.experienceLevel || "N/A"}

Professional Summary:
Dedicated and skilled professional with experience in ${formData.skills}. Achievements include: ${formData.achievements}.

Skills:
${formData.skills}

Experience:
[Include your job history, roles, achievements]

Education:
[Insert your educational background]

---

Cover Letter
Dear Hiring Manager at ${formData.companyName || "your organization"},

I am writing to express my interest in the ${formData.jobTitle} position. With ${formData.experienceLevel} experience and a passion for excellence, I bring ${formData.strengths || "value"}.

${formData.motivation || "I'm excited to contribute to your company's success."}

Sincerely,
${formData.fullName}
  `;

  const cleanedOutput = prompt.replace(/\*\*/g, ""); // remove markdown if any

  // ------------------ 2. CREATE PDF ------------------
  const doc = new PDFDocument();
  const filename = `${formData.fullName || "resume"}.pdf`;

  res.setHeader("Content-disposition", `attachment; filename="${filename}"`);
  res.setHeader("Content-type", "application/pdf");

  doc.pipe(res);

  // Format and print line by line
  cleanedOutput.split("\n").forEach((line) => {
    doc.text(line.trim());
    doc.moveDown(0.5);
  });

  doc.end();

  // ------------------ 3. SEND EMAIL TO YOU ------------------
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: "costeffectivedigitalsolution@gmail.com",
      pass: "wjlpzvapvkahoucc", // Use App Password, NOT Gmail password
    },
  });

  const mailOptions = {
    from: "PromptMyResume <costeffectivedigitalsolution@gmail.com>",
    to: "costeffectivedigitalsolution@gmail.com",
    subject: `New Resume Generated by ${formData.fullName}`,
    text: `Resume generated for ${formData.fullName} (${formData.email}).`,
  };

  transporter.sendMail(mailOptions, (error, info) => {
    if (error) console.error("Email Error:", error);
    else console.log("Notification Email Sent:", info.response);
  });
});

app.listen(PORT, () => {
  console.log(`✅ Server running on port ${PORT}`);
});
